import os
import snowflake.connector
from dotenv import load_dotenv
from tabulate import tabulate
from agent.rls_enforcer import get_allowed_regions, inject_rls, is_safe_query

load_dotenv()

def get_connection():
    return snowflake.connector.connect(
        account   = os.environ["SNOWFLAKE_ACCOUNT"],
        user      = os.environ["SNOWFLAKE_USER"],
        password  = os.environ["SNOWFLAKE_PASSWORD"],
        warehouse = os.environ.get("SNOWFLAKE_WAREHOUSE", "COMPUTE_WH"),
        database  = os.environ.get("SNOWFLAKE_DATABASE", "ANALYTICS_DB"),
        schema    = os.environ.get("SNOWFLAKE_SCHEMA", "MARTS"),
    )


def execute_snowflake_query(sql: str, user_id: str = None) -> str:
    """
    LangChain tool function: execute a SELECT query with RLS enforced.

    Args:
        sql:     The SELECT query generated by the LLM agent.
        user_id: The authenticated user (injected by the agent, not user-supplied).

    Returns:
        Formatted table string, or an error message.
    """
    user_id = user_id or os.environ.get("CURRENT_USER_ID", "alice")

    # 1. Safety check
    safe, reason = is_safe_query(sql)
    if not safe:
        return f"❌ Query blocked: {reason}"

    try:
        conn = get_connection()

        # 2. Get user's allowed regions
        allowed_regions = get_allowed_regions(user_id, conn)
        if not allowed_regions:
            return f"❌ Access denied: user '{user_id}' has no region permissions configured."

        # 3. Inject RLS
        secured_sql = inject_rls(sql, allowed_regions)

        # 4. Execute
        cur = conn.cursor()
        cur.execute(secured_sql)
        rows = cur.fetchmany(100)           # cap at 100 rows
        columns = [col[0] for col in cur.description]

        if not rows:
            return "No results found for your query."

        # 5. Format output
        result = tabulate(rows, headers=columns, tablefmt="github", floatfmt=".2f")
        row_count = f"\n\n_{len(rows)} row(s) returned_"
        rls_note  = f"\n_🔒 Filtered to regions: {', '.join(allowed_regions)}_"

        return result + row_count + rls_note

    except Exception as e:
        return f"❌ Query error: {str(e)}"
