"""
Snowflake query execution with RLS enforcement and write-operation guard.

Security model:
  Every query the LLM generates is wrapped in an INNER JOIN against
  the user's allowed regions before execution. This is done in Python,
  not by the LLM — so it cannot be bypassed via prompt injection.
"""

import os
import snowflake.connector
from dotenv import load_dotenv
from tabulate import tabulate
from agent.rls_enforcer import get_allowed_regions, inject_rls, is_safe_query

load_dotenv()

# Row cap — prevent LLM from pulling unbounded results into context
MAX_ROWS = 100


def _get_connection():
    return snowflake.connector.connect(
        account   = os.environ["SNOWFLAKE_ACCOUNT"],
        user      = os.environ["SNOWFLAKE_USER"],
        password  = os.environ["SNOWFLAKE_PASSWORD"],
        warehouse = os.environ.get("SNOWFLAKE_WAREHOUSE", "COMPUTE_WH"),
        database  = os.environ.get("SNOWFLAKE_DATABASE", "ANALYTICS_DB"),
        schema    = os.environ.get("SNOWFLAKE_SCHEMA", "MARTS"),
    )


def execute_snowflake_query(sql: str, user_id: str = None) -> str:
    """
    Execute a SELECT query with RLS enforced for the given user.

    Args:
        sql:     SELECT query generated by the LLM.
        user_id: Authenticated user — injected by the agent layer, never LLM-supplied.

    Returns:
        Formatted table string with RLS audit note, or a blocked/error message.
    """
    user_id = (user_id or os.environ.get("CURRENT_USER_ID", "alice")).lower()

    # 1. Block all write operations before touching Snowflake
    safe, reason = is_safe_query(sql)
    if not safe:
        return f"❌ {reason}"

    conn = None
    try:
        conn = _get_connection()

        # 2. Fetch user's allowed regions from the security table
        allowed_regions = get_allowed_regions(user_id, conn)
        if not allowed_regions:
            return (
                f"❌ Access denied: user '{user_id}' has no region permissions. "
                "Run setup/01_snowflake_schema.sql and seed the USER_REGION_MAP table."
            )

        # 3. Wrap query with RLS INNER JOIN — cannot be bypassed by the LLM
        secured_sql = inject_rls(sql, allowed_regions)

        # 4. Execute
        cur = conn.cursor()
        cur.execute(secured_sql)
        rows = cur.fetchmany(MAX_ROWS)
        columns = [col[0].lower() for col in cur.description]

        if not rows:
            return (
                f"No data found. "
                f"This may mean no records match your filters within your authorised regions "
                f"({', '.join(allowed_regions)})."
            )

        # 5. Format as markdown table
        table = tabulate(rows, headers=columns, tablefmt="github", floatfmt=",.2f")
        footer = (
            f"\n\n_{len(rows)} row(s) returned"
            f"{' — truncated at ' + str(MAX_ROWS) if len(rows) == MAX_ROWS else ''}_"
            f"\n_🔒 RLS active — filtered to: {', '.join(allowed_regions)}_"
        )
        return table + footer

    except Exception as e:
        return f"❌ Query error: {str(e)}"

    finally:
        if conn:
            conn.close()
